#!/bin/env bash
########################################################################################
# filter...   INPUT OUTPUT FORWARD
# nat...      PREROUTING OUTPUT POSTROUTING
# mangle...   PREROUTING OUTPUT INPUT FORWARD POSTROUTING
# raw...      PREROUTING OUTPUT
# security... INPUT OUTPUT FORWARD
########################################################################################
REMOTE_EXEC=10237
REMOTE_KNOCK=34512
KNOCK_ONE=14560
KNOCK_TWO=56123
KNOCK_THREE=24444
KNOCK_FOUR=13333
########################################################################################
iptables -F
iptables -X
iptables -t filter -F
iptables -t filter -X
iptables -t nat -F
iptables -t nat -X
iptables -t mangle -F
iptables -t mangle -X
iptables -t raw -F
iptables -t raw -X
iptables -t security -F
iptables -t security -X
########################################################################################
iptables -P INPUT DROP
iptables -P OUTPUT ACCEPT
iptables -P FORWARD DROP
########################################################################################
iptables -N LO
iptables -N TCP
iptables -N UDP
iptables -N KNOCK_ONE
iptables -N KNOCK_TWO
iptables -N KNOCK_THREE
iptables -N KNOCK_FOUR
iptables -N AUTH
########################################################################################
iptables -A INPUT -m conntrack --ctstate INVALID -j DROP
#iptables -A INPUT -m recent --name DROPPED --rcheck --seconds 360 --reap -j DROP
iptables -A INPUT -j KNOCK_ONE
########################################################################################
iptables -A INPUT -m recent --name KNOCK_TWO    --rcheck --seconds 60 --reap -j KNOCK_TWO 
iptables -A INPUT -m recent --name KNOCK_THREE  --rcheck --seconds 60 --reap -j KNOCK_THREE
iptables -A INPUT -m recent --name KNOCK_FOUR   --rcheck --seconds 60 --reap -j KNOCK_FOUR
iptables -A INPUT -m recent --name AUTH         --rcheck --seconds 60 --reap -j AUTH
########################################################################################
iptables -A KNOCK_ONE   -p udp --dport ${KNOCK_ONE}   -m recent --set --name KNOCK_TWO
iptables -A KNOCK_TWO   -p udp --dport ${KNOCK_TWO}   -m recent --set --name KNOCK_THREE
iptables -A KNOCK_THREE -p udp --dport ${KNOCK_THREE} -m recent --set --name KNOCK_FOUR
iptables -A KNOCK_FOUR  -p udp --dport ${KNOCK_FOUR}  -m recent --set --name AUTH
iptables -A KNOCK_THREE -m recent --name KNOCK_TWO   --remove
iptables -A KNOCK_FOUR  -m recent --name KNOCK_THREE --remove
iptables -A AUTH        -m recent --name KNOCK_FOUR  --remove 
########################################################################################
iptables -A AUTH -p udp --dport ${REMOTE_EXEC} -j ACCEPT
########################################################################################

iptables -A INPUT -p udp --dport ${REMOTE_KNOCK} -j ACCEPT
iptables -A INPUT -p udp --dport ${REMOTE_EXEC} -j DROP
iptables -A INPUT -m conntrack --ctstate ESTABLISHED,RELATED --ctproto tcp -j ACCEPT
iptables -A INPUT -m conntrack --ctstate ESTABLISHED,RELATED --ctproto udp -j ACCEPT

########################################################################################

iptables -A INPUT -i lo  -m conntrack --ctstate NEW -j LO
iptables -A INPUT -p tcp -m conntrack --ctstate NEW -j TCP
iptables -A INPUT -p udp -m conntrack --ctstate NEW -j UDP
iptables -A INPUT -j LOG --log-prefix "DROPPED" --log-level 6
iptables -A INPUT -j DROP

########################################################################################

iptables -A LO -p tcp -d 127.0.0.1 --dport 6010:6023 -j ACCEPT
iptables -A LO -j LOG --log-prefix "LO" --log-level 6
iptables -A LO -j DROP

########################################################################################

iptables -A TCP -p tcp --dport 12724 -j ACCEPT
iptables -A TCP -p tcp --dport 12725 -j ACCEPT
iptables -A TCP -j LOG --log-prefix "TCP" --log-level 6
iptables -A TCP -j DROP

########################################################################################

iptables -A UDP -j LOG --log-prefix "UDP" --log-level 6
iptables -A UDP -j DROP

########################################################################################
