#!/bin/env bash 
echo -e "Content-type: text/html\n\n"
echo -e "<fieldset><legend><h1>fastcgi params</h1></legend>"

echo -e "query_string: $QUERY_STRING"
echo "<br/>"
echo -e "request_method: $REQUEST_METHOD \n"
echo "<br/>"
echo -e "content_type: $CONTENT_TYPE \n"
echo "<br/>"
echo -e "content_length: $CONTENT_LENGTH \n"
echo "<br/>"
echo -e "script_name: $SCRIPT_NAME \n"
echo "<br/>"
echo -e "request_uri: $REQUEST_URI \n"
echo "<br/>"
echo -e "document_uri: $DOCUMENT_URI \n"
echo "<br/>"
echo -e "document_root: $DOCUMENT_ROOT \n"
echo "<br/>"
echo -e "server_protocol: $SERVER_PROTOCOL \n"
echo "<br/>"
echo -e "https: $HTTPS \n"
echo "<br/>"
echo -e "gateway_interface: $GATEWAY_INTERFACE \n"
echo "<br/>"
echo -e "server_software: $SERVER_SOFTWARE \n"
echo "<br/>"
echo -e "remote_addr: $REMOTE_ADDR \n"
echo "<br/>"
echo -e "remote_port: $REMOTE_PORT \n"
echo "<br/>"
echo -e "server_addr: $SERVER_ADDR \n"
echo "<br/>"
echo -e "server_port: $SERVER_PORT \n"
echo "<br/>"
echo -e "server_name: $SERVER_NAME \n"
echo "<br />"
echo -e "</fieldset>"
